export {default as sendPhoto} from "./sendImage.js"
export {default as addBoard} from "./addBoard.js"
export {default as getAllBoards} from "./getBoards.js"
export {default as getByIdBoard} from "./getByIdBoard.js"
export {default as updateBoard} from "./updateBoard.js"
export {default as removeBoard} from "./removeBoard.js"
export {default as updateBoardActive} from "./updateActive.js"
export {default as sendImage} from "./sendImage.js"